сreated –U postgres MusicLand
CREATE TABLE IF NOT EXISTS Genre(
    ID SERIAL PRIMARY KEY, 
    Genre_Name VARCHAR(40) NOT NULL);
CREATE TABLE IF NOT EXISTS Musician(
    ID SERIAL PRIMARY KEY, 
    First_Name VARCHAR(40) NOT NULL, 
    Nick_Name VARCHAR(40) NOT NULL
    );
CREATE TABLE IF NOT EXISTS Musician_Genre(
    Mus_Gen_ID SERIAL PRIMARY KEY, 
    Musician_ID INTEGER REFERENCES Genre(ID), 
    Genre_ID INTEGER REFERENCES Musician(ID)
    );
CREATE TABLE IF NOT EXISTS Collections(
    ID SERIAL PRIMARY KEY, 
    Collection_Name VARCHAR(60) NOT NULL, 
    Collection_Year DATA NOT NULL
    );
CREATE TABLE IF NOT EXISTS Albums(
    ID SERIAL PRIMARY KEY, 
    Album_Name VARCHAR(60) NOT NULL,
    Album_Year DATA NOT NULL,
    );
CREATE TABLE IF NOT EXISTS Musician_Album(
    ID SERIAL PRIMARY KEY, 
    Musician_ID INTEGER REFERENCES Musician(ID), 
    Albums_ID INTEGER REFERENCES Albums(ID)
    );
CREATE TABLE IF NOT EXISTS Song(
    ID SERIAL PRIMARY KEY, 
    Track_Name VARCHAR(60) NOT NULL,
    Albums_ID INTEGER REFERENCES Albums(ID),
    Track_Time TIME NOT NULL
    );
CREATE TABLE IF NOT EXISTS Collection_Track(
    ID SERIAL PRIMARY KEY, 
    Collect_ID INTEGER REFERENCES Collections(ID), 
    Track_ID INTEGER REFERENCES Song(ID),
    Album_ID INTEGER REFERENCES Albums(ID)
    );